declare module 'react';
declare module 'react-dom';
declare module 'react-router-dom';
declare module 'antd';
declare module '@ant-design/icons';
declare module '*.css';
declare module '*.png';
declare module '*.jpg';
declare module '*.svg'; 